# Use root/example as user/password credentials
version: '3.1'

services:

  mongo-crash-course:
    image: mongo
    volumes:
    - /data:/data/db
    ports:
    - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

# docker-compose up -d 
# docker ps -a (to find container name)
# docker exec -it <container_name> /bin/bash/ (to go into container, use powershell on Windows)
# mongo (run inside the container)